### ISSUE TITLE
Should discuss how to encode EOF in the existing API

### ISSUE THREAD

**Issue by lspitzner** [reflex-frp/reflex-process#7]
`createProcess` does not support this at all; with

https://github.com/reflex-frp/reflex-process/blob/29b83cfcf5e14656c43ad97de31727a81049287a/src/Reflex/Process.hs#L61-L71

you _could_ have `i` be something like `Maybe ByteString` (or `These ByteString ()`) and translate `Nothing` to a `hClose` in the `i -> IO ()` bit (or `This`\~payload, `That`\~EOF). With this approach, the user needs to ensure that the input event becomes `never` after the first `Nothing`.

Maybe there is a better approach to handling this, and in general it would be nice if this library provided some helpers around this.

**Comment by 3noch** [comment]
Instead of using `These` directly, a new `data` type that clearly explains each case would be best, like `SendPipe_Bytes ByteString | SendPipe_EOF (Maybe ByteString)`.

But this is definitely needed. PRs welcome!

**Comment by 3noch** [comment]
Fixed by #15
